from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "src" / "generatedModel.js"

content = """// Generated by scripts/generate_blender_model.py.
// This is an original educational layout manifest, not CAD data.

export const generatedModelMeta = {
  generatedBy: 'python generator',
  purpose: 'museum-style educational abstraction',
  accuracy: 'mechanically plausible, not an exact replica',
  geometryPolicy: 'original simplified geometry only'
}

export const movementZones = [
  { name: 'Going energy', x: -0.56, y: 0.34, radius: 0.29, color: '#d89537' },
  { name: 'Timekeeping train', x: 0.1, y: 0.33, radius: 0.32, color: '#e4c36d' },
  { name: 'Regulator', x: 0.66, y: 0.27, radius: 0.24, color: '#87c6ff' },
  { name: 'Chime energy', x: -0.58, y: -0.33, radius: 0.3, color: '#c0782f' },
  { name: 'Striking train', x: 0.08, y: -0.33, radius: 0.34, color: '#f39a4a' },
  { name: 'Acoustic output', x: 0.55, y: -0.58, radius: 0.28, color: '#f06a5d' }
]

export const visualReviewBaseline = {
  targetScore: 8,
  notes: [
    'separate front-side quadrants',
    'large readable bridges',
    'selective labels',
    'organized calendar-side subdials',
    'visible chime path from barrels to gongs'
  ]
}
"""

OUT.write_text(content, encoding="utf-8")
print(f"generated {OUT.relative_to(ROOT)}")
